import { Mapping } from "../types/mapping.js";

export const operators: Mapping[] = [
    // ── Comparison ────────────────────────────────────────────────────────────
    { pattern: /\\leq/g, replacement: "≤" },
    { pattern: /\\le\b/g, replacement: "≤" },
    { pattern: /\\geq/g, replacement: "≥" },
    { pattern: /\\ge\b/g, replacement: "≥" },
    { pattern: /\\neq/g, replacement: "≠" },
    { pattern: /\\ne\b/g, replacement: "≠" },
    { pattern: /\\approx/g, replacement: "≈" },
    { pattern: /\\approxeq/g, replacement: "≊" },
    { pattern: /\\equiv/g, replacement: "≡" },
    { pattern: /\\sim/g, replacement: "∼" },
    { pattern: /\\simeq/g, replacement: "≃" },
    { pattern: /\\cong/g, replacement: "≅" },
    { pattern: /\\doteq/g, replacement: "≐" },
    { pattern: /\\asymp/g, replacement: "≍" },
    { pattern: /\\ll/g, replacement: "≪" },
    { pattern: /\\gg/g, replacement: "≫" },
    { pattern: /\\propto/g, replacement: "∝" },

    // Precedence relations (longer forms first)
    { pattern: /\\preceq/g, replacement: "⪯" },
    { pattern: /\\prec/g, replacement: "≺" },
    { pattern: /\\succeq/g, replacement: "⪰" },
    { pattern: /\\succ/g, replacement: "≻" },

    // Other comparisons
    { pattern: /\\lesssim/g, replacement: "≲" },
    { pattern: /\\gtrsim/g, replacement: "≳" },
    { pattern: /\\lessgtr/g, replacement: "≶" },
    { pattern: /\\gtrless/g, replacement: "≷" },

    // ── Arithmetic ────────────────────────────────────────────────────────────
    { pattern: /\\cdot/g, replacement: "·" },
    { pattern: /\\times/g, replacement: "×" },
    { pattern: /\\div/g, replacement: "÷" },
    { pattern: /\\pm/g, replacement: "±" },
    { pattern: /\\mp/g, replacement: "∓" },
    { pattern: /\\ast/g, replacement: "∗" },
    { pattern: /\\star/g, replacement: "⋆" },
    { pattern: /\\circ/g, replacement: "∘" },
    { pattern: /\\bullet/g, replacement: "∙" },
    { pattern: /\\diamond/g, replacement: "⋄" },
    { pattern: /\\wr/g, replacement: "≀" },
    { pattern: /\\dagger/g, replacement: "†" },
    { pattern: /\\ddagger/g, replacement: "‡" },
    { pattern: /\\oplus/g, replacement: "⊕" },
    { pattern: /\\ominus/g, replacement: "⊖" },
    { pattern: /\\otimes/g, replacement: "⊗" },
    { pattern: /\\oslash/g, replacement: "⊘" },
    { pattern: /\\odot/g, replacement: "⊙" },
    { pattern: /\\bigcirc/g, replacement: "○" },
    { pattern: /\\setminus/g, replacement: "∖" },
    { pattern: /\\smallsetminus/g, replacement: "∖" },
    { pattern: /\\amalg/g, replacement: "⨿" },
    { pattern: /\\boxplus/g, replacement: "⊞" },
    { pattern: /\\boxminus/g, replacement: "⊟" },
    { pattern: /\\boxtimes/g, replacement: "⊠" },
    { pattern: /\\boxdot/g, replacement: "⊡" },
    { pattern: /\\divideontimes/g, replacement: "⋇" },
    { pattern: /\\ltimes/g, replacement: "⋉" },
    { pattern: /\\rtimes/g, replacement: "⋊" },
    { pattern: /\\leftthreetimes/g, replacement: "⋋" },
    { pattern: /\\rightthreetimes/g, replacement: "⋌" },
    { pattern: /\\curlywedge/g, replacement: "⋏" },
    { pattern: /\\curlyvee/g, replacement: "⋎" },
    { pattern: /\\circleddash/g, replacement: "⊝" },
    { pattern: /\\circledast/g, replacement: "⊛" },
    { pattern: /\\circledcirc/g, replacement: "⊚" },

    // ── Calculus / Analysis ────────────────────────────────────────────────────
    { pattern: /\\infty/g, replacement: "∞" },
    { pattern: /\\partial/g, replacement: "∂" },
    { pattern: /\\nabla/g, replacement: "∇" },
    { pattern: /\\int/g, replacement: "∫" },
    { pattern: /\\iint/g, replacement: "∬" },
    { pattern: /\\iiint/g, replacement: "∭" },
    { pattern: /\\iiiint/g, replacement: "⨌" },
    { pattern: /\\oint/g, replacement: "∮" },
    { pattern: /\\oiint/g, replacement: "∯" },
    { pattern: /\\oiiint/g, replacement: "∰" },
    { pattern: /\\sum/g, replacement: "∑" },
    { pattern: /\\prod/g, replacement: "∏" },
    { pattern: /\\coprod/g, replacement: "∐" },
    { pattern: /\\intop/g, replacement: "∫" },
    { pattern: /\\smallint/g, replacement: "∫" },

    // ── Functions (longer forms first to avoid substring collisions) ──────────
    { pattern: /\\limsup/g, replacement: "lim sup" },
    { pattern: /\\liminf/g, replacement: "lim inf" },
    { pattern: /\\arcsin/g, replacement: "arcsin" },
    { pattern: /\\arccos/g, replacement: "arccos" },
    { pattern: /\\arctan/g, replacement: "arctan" },
    { pattern: /\\sinh/g, replacement: "sinh" },
    { pattern: /\\cosh/g, replacement: "cosh" },
    { pattern: /\\tanh/g, replacement: "tanh" },
    { pattern: /\\coth/g, replacement: "coth" },
    { pattern: /\\sech/g, replacement: "sech" },
    { pattern: /\\csch/g, replacement: "csch" },
    { pattern: /\\lim/g, replacement: "lim" },
    { pattern: /\\log/g, replacement: "log" },
    { pattern: /\\ln/g, replacement: "ln" },
    { pattern: /\\lg/g, replacement: "lg" },
    { pattern: /\\exp/g, replacement: "exp" },
    { pattern: /\\sin/g, replacement: "sin" },
    { pattern: /\\cos/g, replacement: "cos" },
    { pattern: /\\tan/g, replacement: "tan" },
    { pattern: /\\csc/g, replacement: "csc" },
    { pattern: /\\sec/g, replacement: "sec" },
    { pattern: /\\cot/g, replacement: "cot" },
    { pattern: /\\det/g, replacement: "det" },
    { pattern: /\\dim/g, replacement: "dim" },
    { pattern: /\\hom/g, replacement: "hom" },
    { pattern: /\\ker/g, replacement: "ker" },
    { pattern: /\\arg/g, replacement: "arg" },
    { pattern: /\\deg/g, replacement: "deg" },
    { pattern: /\\max/g, replacement: "max" },
    { pattern: /\\min/g, replacement: "min" },
    { pattern: /\\sup/g, replacement: "sup" },
    { pattern: /\\inf/g, replacement: "inf" },
    { pattern: /\\Pr/g, replacement: "Pr" },
    { pattern: /\\gcd/g, replacement: "gcd" },
    { pattern: /\\lcm/g, replacement: "lcm" },
    { pattern: /\\bmod\b/g, replacement: "mod" },

    // ── Set theory / Logic ────────────────────────────────────────────────────
    { pattern: /\\in\b/g, replacement: "∈" },
    { pattern: /\\notin/g, replacement: "∉" },
    { pattern: /\\ni\b/g, replacement: "∋" },
    { pattern: /\\notni/g, replacement: "∌" },
    { pattern: /\\owns/g, replacement: "∋" },
    { pattern: /\\subseteqq/g, replacement: "⫅" },
    { pattern: /\\supseteqq/g, replacement: "⫆" },
    { pattern: /\\Subset/g, replacement: "⋐" },
    { pattern: /\\Supset/g, replacement: "⋑" },
    { pattern: /\\subseteq/g, replacement: "⊆" },
    { pattern: /\\supseteq/g, replacement: "⊇" },
    { pattern: /\\subset/g, replacement: "⊂" },
    { pattern: /\\supset/g, replacement: "⊃" },
    { pattern: /\\sqsubseteq/g, replacement: "⊑" },
    { pattern: /\\sqsupseteq/g, replacement: "⊒" },
    { pattern: /\\sqsubset/g, replacement: "⊏" },
    { pattern: /\\sqsupset/g, replacement: "⊐" },
    { pattern: /\\cup/g, replacement: "∪" },
    { pattern: /\\Cap/g, replacement: "⋒" },
    { pattern: /\\Cup/g, replacement: "⋓" },
    { pattern: /\\cap/g, replacement: "∩" },
    { pattern: /\\sqcup/g, replacement: "⊔" },
    { pattern: /\\sqcap/g, replacement: "⊓" },
    { pattern: /\\vee/g, replacement: "∨" },
    { pattern: /\\wedge/g, replacement: "∧" },
    { pattern: /\\barwedge/g, replacement: "⊼" },
    { pattern: /\\veebar/g, replacement: "⊻" },
    { pattern: /\\doublebarwedge/g, replacement: "⩞" },
    { pattern: /\\emptyset/g, replacement: "∅" },
    { pattern: /\\varnothing/g, replacement: "∅" },
    { pattern: /\\complement/g, replacement: "∁" },
    { pattern: /\\forall/g, replacement: "∀" },
    { pattern: /\\exists/g, replacement: "∃" },
    { pattern: /\\nexists/g, replacement: "∄" },
    { pattern: /\\neg/g, replacement: "¬" },
    { pattern: /\\lnot/g, replacement: "¬" },
    { pattern: /\\land/g, replacement: "∧" },
    { pattern: /\\lor/g, replacement: "∨" },
    { pattern: /\\intercal/g, replacement: "⊺" },

    // ── Logic / Proof ─────────────────────────────────────────────────────────
    { pattern: /\\therefore/g, replacement: "∴" },
    { pattern: /\\because/g, replacement: "∵" },
    { pattern: /\\models/g, replacement: "⊧" },
    { pattern: /\\vdash/g, replacement: "⊢" },
    { pattern: /\\dashv/g, replacement: "⊣" },
    { pattern: /\\bowtie/g, replacement: "⋈" },
    { pattern: /\\mid\b/g, replacement: "∣" },
    { pattern: /\\nmid/g, replacement: "∤" },

    // ── Misc symbols ─────────────────────────────────────────────────────────
    { pattern: /\\perp/g, replacement: "⊥" },
    { pattern: /\\top/g, replacement: "⊤" },
    { pattern: /\\parallel/g, replacement: "∥" },
    { pattern: /\\nparallel/g, replacement: "∦" },
    { pattern: /\\shortparallel/g, replacement: "∥" },
    { pattern: /\\nshortparallel/g, replacement: "∦" },
    { pattern: /\\angle/g, replacement: "∠" },
    { pattern: /\\measuredangle/g, replacement: "∡" },
    { pattern: /\\sphericalangle/g, replacement: "∢" },
    { pattern: /\\triangle/g, replacement: "△" },
    { pattern: /\\triangledown/g, replacement: "▽" },
    { pattern: /\\triangleleft/g, replacement: "◃" },
    { pattern: /\\triangleright/g, replacement: "▹" },
    { pattern: /\\vartriangle/g, replacement: "△" },
    { pattern: /\\vartriangleright/g, replacement: "⊳" },
    { pattern: /\\vartriangleleft/g, replacement: "⊲" },
    { pattern: /\\trianglerighteq/g, replacement: "⊵" },
    { pattern: /\\trianglelefteq/g, replacement: "⊴" },
    { pattern: /\\ntriangleright/g, replacement: "⋫" },
    { pattern: /\\ntriangleleft/g, replacement: "⋪" },
    { pattern: /\\ntrianglerighteq/g, replacement: "⋭" },
    { pattern: /\\ntrianglelefteq/g, replacement: "⋬" },
    { pattern: /\\blacktriangle/g, replacement: "▲" },
    { pattern: /\\blacktriangledown/g, replacement: "▼" },
    { pattern: /\\blacktriangleright/g, replacement: "▶" },
    { pattern: /\\blacktriangleleft/g, replacement: "◀" },
    { pattern: /\\prime/g, replacement: "′" },
    { pattern: /\\doubleprime/g, replacement: "″" },
    { pattern: /\\ell/g, replacement: "ℓ" },
    { pattern: /\\hbar/g, replacement: "ℏ" },
    { pattern: /\\hslash/g, replacement: "ℏ" },
    { pattern: /\\imath/g, replacement: "ı" },
    { pattern: /\\jmath/g, replacement: "ȷ" },
    { pattern: /\\wp/g, replacement: "℘" },
    { pattern: /\\aleph/g, replacement: "ℵ" },
    { pattern: /\\beth/g, replacement: "ℶ" },
    { pattern: /\\gimel/g, replacement: "ℷ" },
    { pattern: /\\daleth/g, replacement: "ℸ" },
    { pattern: /\\Re/g, replacement: "ℜ" },
    { pattern: /\\Im/g, replacement: "ℑ" },
    { pattern: /\\Box/g, replacement: "□" },
    { pattern: /\\Diamond/g, replacement: "◇" },
    { pattern: /\\blacksquare/g, replacement: "■" },
    { pattern: /\\blacklozenge/g, replacement: "⧫" },
    { pattern: /\\bigstar/g, replacement: "★" },
    { pattern: /\\lozenge/g, replacement: "◊" },
    { pattern: /\\circledS/g, replacement: "Ⓢ" },
    { pattern: /\\circledR/g, replacement: "®" },
    { pattern: /\\circledast/g, replacement: "⊛" },
    { pattern: /\\clubsuit/g, replacement: "♣" },
    { pattern: /\\diamondsuit/g, replacement: "♢" },
    { pattern: /\\heartsuit/g, replacement: "♡" },
    { pattern: /\\spadesuit/g, replacement: "♠" },
    { pattern: /\\eth/g, replacement: "ð" },
    { pattern: /\\digamma/g, replacement: "ϝ" },
    { pattern: /\\varkappa/g, replacement: "ϰ" },
    { pattern: /\\Finv/g, replacement: "Ⅎ" },
    { pattern: /\\Game/g, replacement: "⅁" },
    { pattern: /\\backepsilon/g, replacement: "∍" },
    { pattern: /\\backsim/g, replacement: "∽" },
    { pattern: /\\backsimeq/g, replacement: "⋍" },
    { pattern: /\\Bumpeq/g, replacement: "≎" },
    { pattern: /\\bumpeq/g, replacement: "≏" },
    { pattern: /\\Join/g, replacement: "⋈" },
    // Logic / Proof extra
    { pattern: /\\Vdash/g, replacement: "⊩" },
    { pattern: /\\Vvdash/g, replacement: "⊪" },
    { pattern: /\\vDash/g, replacement: "⊨" },
    { pattern: /\\nvDash/g, replacement: "⊭" },
    { pattern: /\\nVDash/g, replacement: "⊯" },
    { pattern: /\\nVdash/g, replacement: "⊮" },
    // Relation symbols
    { pattern: /\\colon/g, replacement: ":" },
    { pattern: /\\dashrightarrow/g, replacement: "⇢" },
    { pattern: /\\dashleftarrow/g, replacement: "⇠" },

    // ── Spacing commands ──────────────────────────────────────────────────────
    { pattern: /\\quad/g, replacement: "    " },
    { pattern: /\\qquad/g, replacement: "        " },
    { pattern: /\\,/g, replacement: " " },
    { pattern: /\\;/g, replacement: " " },
    { pattern: /\\!/g, replacement: "" },
    { pattern: /\\ /g, replacement: " " }, // backslash-space

    // ── LaTeX escape sequences ────────────────────────────────────────────────
    { pattern: /\\#/g, replacement: "#" },
    { pattern: /\\%/g, replacement: "%" },
    { pattern: /\\{/g, replacement: "{" },
    { pattern: /\\}/g, replacement: "}" },
    { pattern: /\\\$/g, replacement: "$" },
    { pattern: /\\_/g, replacement: "_" },
    { pattern: /\\&/g, replacement: "&" },
    { pattern: /\\S/g, replacement: "§" },
    { pattern: /\\P/g, replacement: "¶" },
    { pattern: /\\textbackslash/g, replacement: "\\" },

    // ── Brackets / delimiters ─────────────────────────────────────────────────
    { pattern: /\\left\s*\(/g, replacement: "(" },
    { pattern: /\\right\s*\)/g, replacement: ")" },
    { pattern: /\\left\s*\[/g, replacement: "[" },
    { pattern: /\\right\s*\]/g, replacement: "]" },
    { pattern: /\\left\s*\|/g, replacement: "|" },
    { pattern: /\\right\s*\|/g, replacement: "|" },
    { pattern: /\\lfloor/g, replacement: "⌊" },
    { pattern: /\\rfloor/g, replacement: "⌋" },
    { pattern: /\\lceil/g, replacement: "⌈" },
    { pattern: /\\rceil/g, replacement: "⌉" },
    { pattern: /\\langle/g, replacement: "⟨" },
    { pattern: /\\rangle/g, replacement: "⟩" },

    // ── Number sets ────────────────────────────────────────────────────────────
    { pattern: /\\mathbb\{R\}/g, replacement: "ℝ" },
    { pattern: /\\mathbb\{N\}/g, replacement: "ℕ" },
    { pattern: /\\mathbb\{Z\}/g, replacement: "ℤ" },
    { pattern: /\\mathbb\{Q\}/g, replacement: "ℚ" },
    { pattern: /\\mathbb\{C\}/g, replacement: "ℂ" },
    { pattern: /\\mathbb\{P\}/g, replacement: "ℙ" },
    { pattern: /\\mathbb\{H\}/g, replacement: "ℍ" },
    { pattern: /\\mathbb\{F\}/g, replacement: "𝔽" },

    // ── Dots ──────────────────────────────────────────────────────────────────
    { pattern: /\\ldots/g, replacement: "…" },
    { pattern: /\\cdots/g, replacement: "⋯" },
    { pattern: /\\vdots/g, replacement: "⋮" },
    { pattern: /\\ddots/g, replacement: "⋱" },
];
