import { Mapping } from "../types/mapping.js";

export const operators: Mapping[] = [
    // Comparison
    { pattern: /\\leq/g,      replacement: "≤" },
    { pattern: /\\le\b/g,     replacement: "≤" },
    { pattern: /\\geq/g,      replacement: "≥" },
    { pattern: /\\ge\b/g,     replacement: "≥" },
    { pattern: /\\neq/g,      replacement: "≠" },
    { pattern: /\\ne\b/g,     replacement: "≠" },
    { pattern: /\\approx/g,   replacement: "≈" },
    { pattern: /\\equiv/g,    replacement: "≡" },
    { pattern: /\\sim/g,      replacement: "~" },
    { pattern: /\\simeq/g,    replacement: "≃" },
    { pattern: /\\cong/g,     replacement: "≅" },
    { pattern: /\\ll/g,       replacement: "≪" },
    { pattern: /\\gg/g,       replacement: "≫" },
    { pattern: /\\propto/g,   replacement: "∝" },

    // Arithmetic
    { pattern: /\\cdot/g,     replacement: "·" },
    { pattern: /\\times/g,    replacement: "×" },
    { pattern: /\\div/g,      replacement: "÷" },
    { pattern: /\\pm/g,       replacement: "±" },
    { pattern: /\\mp/g,       replacement: "∓" },
    { pattern: /\\circ/g,     replacement: "∘" },
    { pattern: /\\oplus/g,    replacement: "⊕" },
    { pattern: /\\otimes/g,   replacement: "⊗" },

    // Calculus / Analysis
    { pattern: /\\infty/g,    replacement: "∞" },
    { pattern: /\\partial/g,  replacement: "∂" },
    { pattern: /\\nabla/g,    replacement: "∇" },
    { pattern: /\\int/g,      replacement: "∫" },
    { pattern: /\\iint/g,     replacement: "∬" },
    { pattern: /\\iiint/g,    replacement: "∭" },
    { pattern: /\\oint/g,     replacement: "∮" },
    { pattern: /\\sum/g,      replacement: "Σ" },
    { pattern: /\\prod/g,     replacement: "Π" },
    { pattern: /\\lim/g,      replacement: "lim" },
    { pattern: /\\log/g,      replacement: "log" },
    { pattern: /\\ln/g,       replacement: "ln" },
    { pattern: /\\exp/g,      replacement: "exp" },
    { pattern: /\\sin/g,      replacement: "sin" },
    { pattern: /\\cos/g,      replacement: "cos" },
    { pattern: /\\tan/g,      replacement: "tan" },

    // Set theory / Logic
    { pattern: /\\in\b/g,     replacement: "∈" },
    { pattern: /\\notin/g,    replacement: "∉" },
    { pattern: /\\subset/g,   replacement: "⊂" },
    { pattern: /\\subseteq/g, replacement: "⊆" },
    { pattern: /\\supset/g,   replacement: "⊃" },
    { pattern: /\\supseteq/g, replacement: "⊇" },
    { pattern: /\\cup/g,      replacement: "∪" },
    { pattern: /\\cap/g,      replacement: "∩" },
    { pattern: /\\emptyset/g, replacement: "∅" },
    { pattern: /\\varnothing/g,replacement: "∅" },
    { pattern: /\\forall/g,   replacement: "∀" },
    { pattern: /\\exists/g,   replacement: "∃" },
    { pattern: /\\nexists/g,  replacement: "∄" },
    { pattern: /\\neg/g,      replacement: "¬" },
    { pattern: /\\land/g,     replacement: "∧" },
    { pattern: /\\lor/g,      replacement: "∨" },

    // Misc symbols
    { pattern: /\\perp/g,     replacement: "⊥" },
    { pattern: /\\parallel/g, replacement: "∥" },
    { pattern: /\\angle/g,    replacement: "∠" },
    { pattern: /\\triangle/g, replacement: "△" },
    { pattern: /\\therefore/g,replacement: "∴" },
    { pattern: /\\because/g,  replacement: "∵" },
    { pattern: /\\prime/g,    replacement: "′" },
    { pattern: /\\infty/g,    replacement: "∞" },
    { pattern: /\\ell/g,      replacement: "ℓ" },
    { pattern: /\\Re/g,       replacement: "ℜ" },
    { pattern: /\\Im/g,       replacement: "ℑ" },

    // Spacing commands (remove/replace)
    { pattern: /\\quad/g,     replacement: "    " },
    { pattern: /\\qquad/g,    replacement: "        " },
    { pattern: /\\,/g,        replacement: " " },
    { pattern: /\\;/g,        replacement: " " },
    { pattern: /\\!/g,        replacement: "" },
    { pattern: /\\\s/g,       replacement: " " },

    // Brackets / delimiters
    { pattern: /\\left\s*\(/g,  replacement: "(" },
    { pattern: /\\right\s*\)/g, replacement: ")" },
    { pattern: /\\left\s*\[/g,  replacement: "[" },
    { pattern: /\\right\s*\]/g, replacement: "]" },
    { pattern: /\\left\s*\|/g,  replacement: "|" },
    { pattern: /\\right\s*\|/g, replacement: "|" },
    { pattern: /\\lfloor/g,     replacement: "⌊" },
    { pattern: /\\rfloor/g,     replacement: "⌋" },
    { pattern: /\\lceil/g,      replacement: "⌈" },
    { pattern: /\\rceil/g,      replacement: "⌉" },
    { pattern: /\\langle/g,     replacement: "⟨" },
    { pattern: /\\rangle/g,     replacement: "⟩" },

    // Number sets
    { pattern: /\\mathbb\{R\}/g, replacement: "ℝ" },
    { pattern: /\\mathbb\{N\}/g, replacement: "ℕ" },
    { pattern: /\\mathbb\{Z\}/g, replacement: "ℤ" },
    { pattern: /\\mathbb\{Q\}/g, replacement: "ℚ" },
    { pattern: /\\mathbb\{C\}/g, replacement: "ℂ" },
    { pattern: /\\mathbb\{P\}/g, replacement: "ℙ" },

    // Dots
    { pattern: /\\ldots/g,    replacement: "…" },
    { pattern: /\\cdots/g,    replacement: "⋯" },
    { pattern: /\\vdots/g,    replacement: "⋮" },
    { pattern: /\\ddots/g,    replacement: "⋱" },
];